language: julia

os:
- linux

julia:
- 1.0

install:
- julia --project=project/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate(); Pkg.build()'

script:
- julia --project=project/ test/runtests.jl
