language: julia
os:
    - osx
    - linux
julia:
    - release
    - nightly
notifications:
    email: false
script:
    - julia -e 'Pkg.clone(pwd()); Pkg.build("JuliaByExample"); Pkg.test("JuliaByExample")';