language: julia

os:
- linux

julia:
- 1.0

install:
- julia --project=testing/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'

script:
- julia --project=testing/ test/runtests.jl
